#!/usr/bin/env bash
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.

export BLACK="\033[0;30m";
export BLACK_BOLD="\033[1;30m";

export RED="\033[0;31m";
export RED_BOLD="\033[1;31m";

export GREEN="\033[0;32m";
export GREEN_BOLD="\033[1;32m";

export YELLOW="\033[0;33m";
export YELLOW_BOLD="\033[1;33m";

export BLUE="\033[0;34m";
export BLUE_BOLD="\033[1;34m";

export MAGENTA="\033[0;35m";
export MAGENTA_BOLD="\033[1;35m";

export CYAN="\033[0;36m";
export CYAN_BOLD="\033[1;36m";

export WHITE="\033[0;37m";
export WHITE_BOLD="\033[1;37m";

export BG_BLACK="\033[0;40m";
export BG_BLACK_BOLD="\033[1;40m";

export BG_RED="\033[0;41m";
export BG_RED_BOLD="\033[1;41m";

export BG_GREEN="\033[0;42m";
export BG_GREEN_BOLD="\033[1;42m";

export BG_YELLOW="\033[0;43m";
export BG_YELLOW_BOLD="\033[1;43m";

export BG_BLUE="\033[0;44m";
export BG_BLUE_BOLD="\033[1;44m";

export BG_MAGENTA="\033[0;45m";
export BG_MAGENTA_BOLD="\033[1;45m";

export BG_CYAN="\033[0;46m";
export BG_CYAN_BOLD="\033[1;46m";

export BG_WHITE="\033[0;47m";
export BG_WHITE_BOLD="\033[1;47m";

export NO_EFFECTS="\033[m";

if [[ "$TERM" = "linux" ]]; then
    echo -en "\e]P0000000" #black
    echo -en "\e]P83f3f3f" #darkgrey
    echo -en "\e]P19f3f3f" #darkred
    echo -en "\e]P9ff9f9f" #red
    echo -en "\e]P23f9f3f" #darkgreen
    echo -en "\e]PAbfefbf" #green
    echo -en "\e]P3bf9f3f" #brown
    echo -en "\e]PB9fff9f" #yellow
    echo -en "\e]P45f5f9f" #darkblue
    echo -en "\e]PC9f9fff" #blue
    echo -en "\e]P59f3f9f" #darkmagenta
    echo -en "\e]PDff9fff" #magenta
    echo -en "\e]P63f9f9f" #darkcyan
    echo -en "\e]PE9fffff" #cyan
    echo -en "\e]P7afafaf" #lightgrey
    echo -en "\e]PFffffff" #white
    clear #for background artifacting
fi
