#!/usr/bin/env bash
#-*- coding: utf-8; mode:shell-script -*-
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.

## User-defined bashrc extensions

function python_ver() {
	python --version |cut -d "." -f1,2 |sed 's/ //' |sed 's/P/p/'
}

# Identify self
export RUNCOMDIR="${HOME}/.runcom"

PATH="${PATH}:${HOME}/bin";
export PATH="${PATH}:${HOME}/.local/bin";

# Python exports
export PYTHONPATH="${PYTHONPATH}:${HOME}/lib/$(python_ver)/site-packages:${HOME}/lib64/$(python_ver)/site-packages";

# C(++) exports
export LD_LIBRARY_PATH="${HOME}/.local/lib:${HOME}/.local/lib64";

# GPU exports
export PYOPENCL_CTX='0';
export PYOPENCL_COMPILER_OUTPUT=1;
export OCL_ICD_VENDORS="/etc/OpenCL/vendors/";

# WLROOTS (sway) Don't really remember why these were made
# export WLR_BACKENDS="headless";
# export WLR_LIBINPUT_NO_DEVICES=1;
