#! /usr/bin/env bash
function git_status() {
  local modified=0
  local cached=0
  local untracked=0

  while read -r line; do
    if [ "$line" = '_?_?_' ]; then
      untracked=1
      continue
    fi

    if [[ "$line" =~ ^_[^[:space:]]_.?_ ]]; then
      cached=1
    fi

    if [[ "$line" =~ ^_._[^[:space:]]_ ]]; then
      modified=1
    fi
  done < <(git status --short | cut -b -2 | sed -e 's/\(.\)\(.*\)/_\1_\2_/')

  if [ $modified -ne 0 ]; then
    echo -ne "${RED}M"
  fi

  if [ $cached -ne 0 ]; then
    echo -ne "${GREEN}C"
  fi

  if [ $untracked -ne 0 ]; then
    echo -ne "${RED}?"
  fi

  if [ -n "$(git stash list)" ]; then
    echo -ne "${CYAN}S"
  fi
  echo -e "${NO_EFFECTS}"
}

function git_branch() {
  local branch
  branch="$(git branch 2>/dev/null | grep '^\*' | sed -e "s/^* //")"
  if [[ "${branch}" =~ ^bug- ]]; then
    echo -ne "${GREEN}"
  elif [[ "${branch}" =~ ^atc- ]]; then
    echo -ne "${CYAN}"
  elif [[ "${branch}" =~ ^tmp ]]; then
    echo -ne "${MAGRNTA}"
  elif [[ "${branch}" = "(detached from hde/master)" ]]; then
    echo -ne "${YELLOW}"
  elif [[ "${branch}" == "master" ]]; then
      return
  else
    echo -ne "${BLUE}"
  fi
  echo -n "${branch}"
  echo -e "${NO_EFFECTS}"
}

function git_hash() {
  git log --pretty=format:'%h' -n 1
}

function git_ps() {
  if ! git status --ignore-submodules &>/dev/null; then
    return
  else
      echo "[$(git_branch)·$(git_hash)·$(git_status)]"
  fi
}
