#!/usr/bin/env bash
#-*- coding: utf-8; mode:shell-script -*-
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.

## User-defined bashrc extensions
##	prompt script

PS1=""
PS1="${PS1}\n"
PS1="${PS1}\[${GREEN}\]\u\[${NO_EFFECTS}\]"
PS1="${PS1}@"
PS1="${PS1}\[${BLUE}\]\h\[${NO_EFFECTS}\]"
PS1="${PS1}\$(git_ps)"
PS1="${PS1}\[${WHITE}\]<"
PS1="${PS1}\[${CYAN}\]\W"
PS1="${PS1}\[${WHITE}\]>"
PS1="${PS1}\[${YELLOW}\]\t\[${NO_EFFECTS}\]"
PS1="${PS1}\n» "

PS2=""
PS2="${PS2}\[${CYAN}\]cont..."
PS2="${PS2}\[${NO_EFFECTS}\]"
PS2="${PS2}» ";

PS3="Selection: ";

export PS1
export PS2
export PS3
