#!/usr/bin/env bash
#-*- coding: utf-8; mode:shell-script -*-
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.

for term in foot termite tilix xterm gnome-terminal; do
    if [[ -n "$(command -v $term)" ]]; then
        export defterm="$term";
        break;
    fi;
done

# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
    # export DISPLAY=":0.0"
    # export WAYLAND_DISPLAY=wayland-0
    export XDG_SESSION_TYPE=wayland
    export SDL_VIDEODRIVER=wayland
    export QT_QPA_PLATFORM=wayland-egl
    export ELM_DISPLAY=wl
    export ECORE_EVAS_ENGINE=wayland_egl
    export ELM_ENGINE=wayland_egl
    export ELM_ACCEL=opengl
    export GDK_BACKEND=wayland
    unset GDK_BACKEND
    export DBUS_SESSION_BUS_ADDRESS
    export DBUS_SESSION_BUS_PID
    export MOZ_ENABLE_WAYLAND=1
    # unset WAYLAND_DISPLAY
    exec sway
fi
