#!/usr/bin/env bash
# -*- coding: utf-8; mode:shell-script -*-
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.


# compress
## Use multiple threads
alias tcpz="tar -c --use-compress-program=pigz ";
alias txpz="tar -x --use-compress-program=pigz ";

deconvolute() {
    if [[ ! -f "$1" ]]; then
        echo "$1: no such file";
    else
        case "$1" in
            *.tar.bz2)
                tar -xjf "$1"
                ;;
            *.tbz2)
                tar -xjf "$1"
                ;;
            *.tar.gz)
                tar -x --use-compress-program=pigz -f "$1"
                ;;
            *.tgz)
                tar -x --use-compress-program=pigz -f "$1"
                ;;
            *.gz)
                pigz "$1"
                ;;
            *.rar)
                unrar -x "$1"
                ;;
            *.tar)
                tar -xf "$1"
                ;;
            *.zip)
                unzip "$1"
                ;;
            *.tar.xz)
                tar -xf "$1"
                ;;
            *)
                echo "Cannot extract $1, provide explicit command"
        esac
    fi
}

# ripgrep is better than grep
for sc in "rg" "ag" "pt" "ack" "grep"; do
    if hash "$sc"; then
        alias grep="$sc";
        break
    fi
done

# List Contents
alias ls="exa -Fh --color=auto"; ## always list human readable
alias la='exa -a --color=auto'; ## List almost all
alias ll='exa -lr -s size'; ## list files sorted by size, human readable
alias lla='exa -a'; ## List almost all in detail
alias l.='exa -a --color=auto |grep "^\."'; # list hidden dot files
alias sl="sl -al"; ## steamlocomotive

# disk usage
alias du='du -hc'; ## Always list human readable, total
alias df='df -h'; ## Always list human readable, total
alias duall="du -hc |grep '^[3-9]\{3\}M\|^[0-9]\{0,3\}\.\{0,1\}[0-9]\{0,1\}G'";

# Network
alias nload="nload -u M -U G -t 10000 -a 3600 "$(ip a | grep -m 1 " UP " | cut -d " " -f 2 | cut -d ":" -f 1)""
alias nethogs="\su - -c \"nethogs $(ip a |grep  'state UP' | cut -d ' ' -f 2 | cut -d ':' -f 1) -d 10\"";
alias ping="ping -c 4 ";

# Environment
alias su=" su -"; ## become root with variables
alias sourceit="source ~/.bashrc";
alias to_venv="source .venv/bin/activate";
alias activateGRN="deactivate || true; source ${HOME}/.virtualenvs/Leish_Petri/bin/activate";
alias activateVIS="deactivate || true; source ${HOME}/.virtualenvs/visualize/bin/activate";
alias activateRNA="deactivate || true; source ${HOME}/.virtualenvs/RNASeq3/bin/activate";

# Monitor Jobs
alias qstatf="while true; do date; ssh paranjpe@192.168.14.20 qstat -f; sleep 900; done;";
alias qstat="while true; do date; ssh paranjpe@192.168.14.20 qstat ; sleep 900; done;";
alias watch="watch -n 10 --color";
alias psauxgrep="ps aux |head -1 && ps aux | grep -v 'grep' | grep -v 'rg'| grep -i";

# Remote logins
alias work_PC7="ssh -X prady@${PC7ip}";
alias HPCconnect="ssh paranjpe@${HPC}"
function copy_to_HPC() {
    scp "$@" "paranjpe@${HPC}:/home/paranjpe/prady_data/";
}

# Better program defaults
alias ex="nvim"; ## always open vim in normal mode
alias vim="nvim"; ## always use neo
alias docker="podman";  # Podman is drop-in replacement for docker

# Lazy one-hand
alias qqqq="exit";
