#!/usr/bin/env bash
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.


dec2hex() {
	echo "hex:"
	echo "obase=16; $@"| bc
	echo "dec:"
	echo "ibase=16; $@"| bc
}

mathcalc() {
	echo "scale=4; $@"| bc
}

pdfcompile() {
	pdflatex $1
	for ext in toc log aux; do
		delfile=${1/\.tex/\.$ext}
		[[ -f "$delfile" ]] && rm "$delfile"
	done
	evince ${1/\.tex/\.pdf}
}

deactivate() {
	# assume that python virtual environments are not active
	true
}
