#!/usr/bin/env bash
#
# Copyright 2020 Pradyumna Paranjape
#
# This file is part of Prady_runcom.
#
# Prady_runcom is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Prady_runcom is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Prady_runcom.  If not, see <https://www.gnu.org/licenses/>.


function dec2hex() {
	echo "hex:"
	echo "obase=16; $@"| bc
	echo "dec:"
	echo "ibase=16; $@"| bc
}

function mathcalc() {
	echo "scale=4; $@"| bc
}

function pdfcompile() {
	pdflatex $1
	for ext in toc log aux; do
		delfile=${1/\.tex/\.$ext}
		[[ -f "$delfile" ]] && rm "$delfile"
	done
	evince ${1/\.tex/\.pdf}
}

function deactivate() {
	# assume that python virtual environments are not active
	true
}

function org2export() {
    # Usage: org2oth [-f] <infile> <othtype>
    proceed=
    while test $# -gt 1; do
        case "$1" in
            -f|--force)
                proceed=true
                shift 1
                ;;
            *)
                infile="${1}"
                shift 1
                ;;
        esac
    done
    if [[ "${1}" == "pdf" ]]; then
        target="latex"
    else
        target="${1}"
    fi
    tarext="${1}"
    if [[ "$infile" == *.org ]]; then
        proceed=true
    else
        echo "Input file should be an org file"
    fi
    if [[ -n "$proceed" ]]; then
        pandoc -f org -t "${target}" -o "${infile/.org/}.${tarext}" "$infile"
    fi
    proceed=
    target=
    infile=
}

function org2doc () {
    org2export "$@" "docx"
}

function org2pdf () {
    org2export "$@" "pdf"
}

function doc2org() {
    if [[ "$1" == *.docx ]]; then
        pandoc -f docx -t org -o  "${1/%docx/org}" "$1"
    else
        echo "Input file must be a docx file"
    fi
}

function gui () {
    nohup "$@" &>/dev/null 0<&- &
    exit
}
