.TH "Info about current IP" "1" 

.SH "Description"
.PP
Wait on command, abort if timed out.
Default: print net info within 5 seconds.

.SH "Code"
.PP
Following section tangles code.

.SS "Handle global variables and exits"
nil
.SS "Parse command"
nil
.SS "Execution"
.SS "Guess and print net info"
.PP
The \fBOLDEST\fP part of prady_runcom...
.IP \(em 4
... although, amended many times
.IP \(em 4
see [[\fInetcheck.org\fP]

.SS "Main routine call"
nil
