.TH "Wayland start graphics ui" "1" 

.SH "Description"
.PP
Start wayland similar to startx.

.SH "Code"
.SS "Header"
.PP
This section tangles the code (POSIX)
.SS "Variables"
.PP
With dbus-run-session under wayland, we don't define DISPLAY
.SS "Parse command line arguments"
nil
.SS "Parse files"
nil
.SS "Launch"
nil
.SS "Entry-Point"
nil
