# -*-coding:utf-8; mode:org -*-
#+TITLE: QuteBrowser Settings
#+AUTHOR: Pradyumna Paranjape
#+EMAIL: pradyparanjpe@rediffmail.com
#+LANGUAGE: en
#+OPTIONS: toc: t mathjax:t TeX:t num:t ::t :todo:nil tags:nil *:t skip:t
#+STARTUP: overview
#+PROPERTY: header-args :tangle config.py

* Table of Contents                                                     :toc:
- [[#what-is-this][What is This]]
- [[#documentation][Documentation:]]
- [[#autoconfig][Autoconfig]]
  - [[#description][Description]]
  - [[#type][Type]]
- [[#cookies][Cookies]]
  - [[#description-1][Description]]
  - [[#type-string][Type: String]]
    - [[#valid-values][Valid values]]
- [[#user-agent][User agent]]
  - [[#type-1][Type:]]
- [[#images][Images]]
  - [[#description-2][Description]]
  - [[#type-2][Type]]
- [[#javascript][Javascript]]
  - [[#description-3][Description]]
  - [[#type-3][Type]]
- [[#dark-mode][Dark Mode]]
  - [[#description-4][Description]]
    - [[#dont-use-themes-from-solarized-everything-css][DONT use themes from solarized-everything-css]]
- [[#custom-remaps][Custom Remaps]]
  - [[#description-5][Description]]
    - [[#aliases][Aliases]]
    - [[#bindings][Bindings]]
    - [[#zathura-pop-out][ZATHURA Pop Out]]
    - [[#mpv-pop-out][MPV Pop Out]]
    - [[#pages][Pages]]
    - [[#search-engines][Search Engines]]
    - [[#fonts][Fonts]]
    - [[#colors][colors]]
    - [[#space-qute][Space /qute/]]

* What is This
  Qutebrowser's config.py written in Org Mode for management

  NOTE: config.py is intended for advanced users who are comfortable
  with manually migrating the config file on qutebrowser upgrades. If
  you prefer, you can also configure qutebrowser using the
  :set/:bind/:config-* commands without having to write a config.py
  file.

* Documentation:
  qute://help/configuring.html
  qute://help/settings.html

* Autoconfig
** Description
   Still Load settings from autoconfig.yml
** Type
   Function call
   This has been uncommented to disable
   #+BEGIN_SRC python
     config.load_autoconfig(False)
   #+END_SRC

* Cookies
** Description
   Which cookies to accept. With QtWebEngine, this setting also controls
   other features with tracking capabilities similar to those of cookies;
   including IndexedDB, DOM storage, filesystem API, service workers, and
   AppCache. Note that with QtWebKit, only `all` and `never` are
   supported as per-domain values. Setting `no-3rdparty` or `no-
   unknown-3rdparty` per-domain on QtWebKit will have the same effect as
   `all`. If this setting is used with URL patterns, the pattern gets
   applied to the origin/first party URL of the page making the request,
   not the request URL.
** Type: String
*** Valid values
    - all: Accept all cookies.
    - no-3rdparty: Accept cookies from the same origin only. This is known to break some sites, such as GMail.
    - no-unknown-3rdparty: Accept cookies from the same origin only, unless a cookie is already set for the domain. On QtWebEngine, this is the same as no-3rdparty.
    - never: Don't accept cookies at all.
    #+BEGIN_SRC python
      config.set('content.cookies.accept', 'all', 'chrome-devtools://*')
      config.set('content.cookies.accept', 'all', 'devtools://*')
    #+END_SRC

* User agent
  The following placeholders are defined:  *
  `{os_info}`: Something like "X11; Linux x86_64". * `{webkit_version}`:
  The underlying WebKit version (set to a fixed value   with
  QtWebEngine). * `{qt_key}`: "Qt" for QtWebKit, "QtWebEngine" for
  QtWebEngine. * `{qt_version}`: The underlying Qt version. *
  `{upstream_browser_key}`: "Version" for QtWebKit, "Chrome" for
  QtWebEngine. * `{upstream_browser_version}`: The corresponding
  Safari/Chrome version. * `{qutebrowser_version}`: The currently
  running qutebrowser version.  The default value is equal to the
  unchanged user agent of QtWebKit/QtWebEngine.  Note that the value
  read from JavaScript is always the global value. With QtWebEngine
  between 5.12 and 5.14 (inclusive), changing the value exposed to
  JavaScript requires a restart.
** Type:
   FormatString
   #+BEGIN_SRC python
     config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}', 'https://web.whatsapp.com/')
     config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://accounts.google.com/*')
     config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36', 'https://*.slack.com/*')
     config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://docs.google.com/*')
     config.set('content.headers.user_agent', 'Mozilla/5.0 ({os_info}; rv:71.0) Gecko/20100101 Firefox/71.0', 'https://drive.google.com/*')
   #+END_SRC

* Images
** Description
   Load images automatically in web pages.
** Type
   Bool
   #+BEGIN_SRC python
     config.set('content.images', True, 'chrome-devtools://*')
     config.set('content.images', True, 'devtools://*')
   #+END_SRC

* Javascript
** Description
   Enable JavaScript.
** Type
   Bool
   #+BEGIN_SRC python
     config.set('content.javascript.enabled', True, 'chrome-devtools://*')
     config.set('content.javascript.enabled', True, 'devtools://*')
     config.set('content.javascript.enabled', True, 'chrome://*/*')
     config.set('content.javascript.enabled', True, 'qute://*/*')
   #+END_SRC

* Dark Mode
** Description
   View sites in dark mode. Most light backgrounds are darkened.
   Sometimes by inverting colors.
   This line can be used for global standard qutebrowser dark mode
*** DONT use themes from solarized-everything-css
    css = [[https://github.com/alphapapa/solarized-everything-css/]['~/.pspman/programs/solarized-everything-css]]/css/'
    config.bind(' th', f'config-cycle content.user_stylesheets {css}/apprentice/apprentice-all-sites.css {css}/darculized/darculized-all-sites.css {css}/gruvbox/gruvbox-all-sites.css {css}/solarized-dark/solarized-dark-all-sites.css ""')
    config.bind(' ht', f'config-cycle content.user_stylesheets "" {css}/solarized-dark/solarized-dark-all-sites.css {css}/gruvbox/gruvbox-all-sites.css {css}/darculized/darculized-all-sites.css {css}/apprentice/apprentice-all-sites.css')
    #+BEGIN_SRC python
      config.set("colors.webpage.darkmode.enabled", True)
    #+END_SRC

* Custom Remaps
** Description
   Customized Remaps for better navigation
   Defined by Pradyumna

*** Aliases
    #+BEGIN_SRC python
      c.aliases = {'q': 'quit', 'w': 'session-save', 'wq': 'quit --save'}
    #+END_SRC

*** Bindings
    #+BEGIN_SRC python
      config.bind('xt', 'config-cycle tabs.show always never')
      config.bind('xb', 'config-cycle statusbar.show always never')
      config.bind('xx', 'config-cycle statusbar.show always never;; config-cycle tabs.show always never')
      config.bind('H', 'tab-prev')
      config.bind('L', 'tab-next')
      config.bind('K', 'back')
      config.bind('J', 'forward')
    #+END_SRC

*** ZATHURA Pop Out
    #+BEGIN_SRC python
      config.bind(' z',
                  'hint links spawn --detach zathura {hint-url}')
    #+END_SRC

*** MPV Pop Out
    #+BEGIN_SRC python
      config.bind(' v',
                  'hint links spawn --detach mpv --force-window yes {hint-url}')
    #+END_SRC

*** Pages
    Start
    Default
    #+BEGIN_SRC python
      c.url.start_pages = ['https://www.anubandha.home/']
      c.url.default_page = 'http://www.anubandha.home/'
    #+END_SRC

*** Search Engines
    #+BEGIN_SRC python
      c.url.searchengines = {
          'DEFAULT': 'http://searx.anubandha.home/searx/search?q={}',
          'g': 'https://www.google.com/?q={}',
          'dg': 'https://www.duckduckgo.com/?q={}',
          'a2': 'https://alternativeto.net/browse/search?q={}',
          'dh': 'https://hub.docker.com/search?q={}&type=image',
          'pip': 'https://pypi.org/search/?q={}',
      }
    #+END_SRC

*** Fonts
    #+BEGIN_SRC python
      c.fonts.default_family = ['Fira Code Retina']
      c.fonts.default_size = '20px'
      c.fonts.web.size.default = 20
      c.fonts.web.size.default_fixed  = 20
      c.fonts.web.size.minimum = 12
      c.fonts.web.size.minimum_logical = 12
    #+END_SRC

*** colors
    #+BEGIN_SRC python
      c.colors.hints.bg = '#bfdfff'
      c.colors.hints.fg = '#402000'
      c.colors.hints.match.fg = c.colors.hints.bg
    #+END_SRC

*** Space /qute/
    Behave like spacemacs
    Common space-bindings added
    #+BEGIN_SRC python
      config.bind('  ', 'set-cmd-text :')
      config.bind(' qr', 'restart')
      config.bind(' qq', 'quit')
      config.bind(' ff', 'set-cmd-text -s :open -t')
      config.bind(' bd', 'tab-close')
    #+END_SRC
