let s:modules = has('nvim') ? stdpath('config') . '/modules' : '~/.vim/modules'
exe 'source' s:modules . '/00-init.vim'
exe 'source' s:modules . '/10-cursor.vim'
exe 'source' s:modules . '/20-settings.vim'
exe 'source' s:modules . '/30-maps.vim'
exe 'source' s:modules . '/40-hooks.vim'
exe 'source' s:modules . '/50-plugins.vim'
exe 'source' s:modules . '/60-colors.vim'
autocmd BufNewFile,BufRead *.py exe 'source' s:modules . '/61-pycolors.vim'
exe 'source' s:modules . '/A0-gui.vim'
