#-*- coding:utf-8; mode:org -*-
#+TITLE: MPV Confit
#+AUTHOR: Pradyumna Paranjape
#+EMAIL: pradyparanjpe@rediffmail.com
#+LANGUAGE: en
#+OPTIONS: toc: t mathjax:t TeX:t num:t ::t :todo:nil tags:nil *:t skip:t
#+STARTUP: overview
#+PROPERTY: header-args :tangle
* Table of Contents :TOC:
- [[#mpv-input-config][mpv Input Config]]
    - [[#location-of-user-defined-bindings][Location of user-defined bindings:]]
  - [[#instructions][Instructions]]
    - [[#list-of-commands-and-further-details][List of commands and further details:]]
    - [[#list-of-special-keys][List of special keys:]]
    - [[#keybindings-testing-mode][Keybindings testing mode:]]
    - [[#use-ignore-to-unbind-a-key-fully][Use 'ignore' to unbind a key fully:]]
    - [[#strings-need-to-be-quoted-and-escaped][Strings need to be quoted and escaped:]]
    - [[#you-can-use-modifier-key-combinations-like-shiftleft-or-ctrlaltx-with][You can use modifier-key combinations like Shift+Left or Ctrl+Alt+x with]]
    - [[#the-default-keybindings-are-hardcoded-into-the-mpv-binary][The default keybindings are hardcoded into the mpv binary.]]
    - [[#developer-note][Developer note:]]
  - [[#keybindings][Keybindings]]
    - [[#if-this-is-enabled-treat-all-the-following-bindings-as-default][If this is enabled, treat all the following bindings as default.]]
    - [[#mouse-wheels-touchpad-or-other-input-devices-that-have-axes][Mouse wheels, touchpad or other input devices that have axes]]
    - [[#seek-units-are-in-seconds-but-note-that-these-are-limited-by-keyframes][Seek units are in seconds, but note that these are limited by keyframes]]
    - [[#do-smaller-always-exact-non-keyframe-limited-seeks-with-shift][Do smaller, always exact (non-keyframe-limited), seeks with shift.]]
    - [[#skip-to-previousnext-subtitle][Skip to previous/next subtitle]]
    - [[#adjust-timing-to-previousnext-subtitle][Adjust timing to previous/next subtitle]]
    - [[#move-video-rectangle][Move video rectangle]]
    - [[#zoomunzoom-video][Zoom/unzoom video]]
    - [[#reset-video-zoompan-settings][Reset video zoom/pan settings]]
    - [[#toggle-deinterlacer-automatically-inserts-or-removes-required-filter][toggle deinterlacer (automatically inserts or removes required filter)]]
    - [[#stretch-ssaass-subtitles-with-anamorphic-videos-to-match-historical][stretch SSA/ASS subtitles with anamorphic videos to match historical]]
    - [[#switch-between-applying-no-style-overrides-to-ssaass-subtitles][switch between applying no style overrides to SSA/ASS subtitles]]
    - [[#cycle-video-aspect-ratios--1-is-the-container-aspect][cycle video aspect ratios; "-1" is the container aspect]]
    - [[#legacy-bindings-may-or-may-not-be-removed-in-the-future][Legacy bindings (may or may not be removed in the future)]]
    - [[#not-assigned-by-default][Not assigned by default]]
    - [[#added-by-prady][Added by Prady]]
- [[#mpv-config][mpv Config]]
  - [[#instructions-1][Instructions]]
    - [[#warning][Warning:]]
    - [[#configuration-files][Configuration files]]
    - [[#profiles][Profiles]]
  - [[#video-settings][video settings]]
    - [[#start-in-fullscreen-mode-by-default][Start in fullscreen mode by default.]]
    - [[#force-starting-with-centered-window][Force starting with centered window]]
    - [[#dont-allow-a-new-window-to-have-a-size-larger-than-90-of-the-screen-size][Don't allow a new window to have a size larger than 90% of the screen size]]
    - [[#do-not-close-the-window-on-exit][Do not close the window on exit.]]
    - [[#do-not-wait-with-showing-the-video-window-until-it-has-loaded][Do not wait with showing the video window until it has loaded.]]
    - [[#disable-the-on-screen-controller-osc][Disable the On Screen Controller (OSC).]]
    - [[#keep-the-player-window-on-top-of-all-other-windows][Keep the player window on top of all other windows.]]
    - [[#specify-high-quality-video-rendering-preset][Specify high quality video rendering preset]]
    - [[#force-video-to-lock-on-the-displays-refresh-rate][Force video to lock on the display's refresh rate,]]
    - [[#enable-hardware-decoding-if-available][Enable hardware decoding if available.]]
  - [[#audio-settings][audio settings]]
    - [[#specify-default-audio-device][Specify default audio device.]]
    - [[#do-not-filter-audio-to-keep-pitch-when-changing-playback-speed][Do not filter audio to keep pitch when changing playback speed.]]
    - [[#output-51-audio-natively-and-upmixdownmix-audio-with-a-different-format][Output 5.1 audio natively, and upmix/downmix audio with a different format.]]
    - [[#disable-any-automatic-remix-_if_-the-audio-output-accepts-the-audio-format][Disable any automatic remix, _if_ the audio output accepts the audio format.]]
  - [[#disguise][Disguise]]
    - [[#pretend-to-be-a-web-browser][Pretend to be a web browser.]]
  - [[#cache-settings][Cache settings]]
    - [[#use-a-large-seekable-ram-cache-even-for-local-input][Use a large seekable RAM cache even for local input.]]
    - [[#use-extra-large-ram-cache-needs-cacheyes-to-make-it-useful][Use extra large RAM cache (needs cache=yes to make it useful).]]
    - [[#disable-the-behavior-that-the-player-will-pause-if-the-cache-goes-below-a][Disable the behavior that the player will pause if the cache goes below a]]
    - [[#store-cache-payload-on-the-hard-disk-instead-of-in-ram][Store cache payload on the hard disk instead of in RAM.]]
    - [[#youtube-downloads][Youtube Downloads]]
  - [[#language][Language]]
    - [[#display-english-subtitles-if-available][Display English subtitles if available.]]
    - [[#play-marathi-audio-if-available-fall-back-to-hindi-english-otherwise][Play Marathi audio if available, fall back to Hindi, English otherwise.]]
    - [[#change-subtitle-encoding-for-arabic-subtitles-use-cp1256][Change subtitle encoding. For Arabic subtitles use 'cp1256'.]]
  - [[#include-path][Include Path]]
  - [[#profiles-1][Profiles]]
  - [[#the-following-profile-can-be-enabled-on-the-command-line-with---profilenight][The following profile can be enabled on the command line with: --profile=night]]

* mpv Input Config
*** Location of user-defined bindings:
    ~/.config/mpv/input.conf

** Instructions
   # Lines starting with # are comments. Use SHARP to assign the # key.
*** List of commands and further details:
    DOCS/man/input.rst
*** List of special keys:
    --input-keylist
*** Keybindings testing mode:
    mpv --input-test --force-window --idle

*** Use 'ignore' to unbind a key fully:
    ctrl+a ignore

*** Strings need to be quoted and escaped:
    KEY show-text "This is a single backslash: \\ and a quote: \" !"

*** You can use modifier-key combinations like Shift+Left or Ctrl+Alt+x with
    Shift, Ctrl, Alt and Meta (may not work on the terminal).

*** The default keybindings are hardcoded into the mpv binary.
    You can disable them completely with: --no-input-default-bindings

*** Developer note:
    On compilation, this file is baked into the mpv binary, and all lines are
    uncommented (unless '#' is followed by a space) - thus this file defines the
    default key bindings.

** Keybindings
*** If this is enabled, treat all the following bindings as default.
    #+begin_src conf :tangle no
      default-bindings start

      MBTN_LEFT     ignore              # don't do anything
      MBTN_LEFT_DBL cycle fullscreen    # toggle fullscreen on/off
      MBTN_RIGHT    cycle pause         # toggle pause on/off
      MBTN_BACK     playlist-prev
      MBTN_FORWARD  playlist-next
    #+end_src

*** Mouse wheels, touchpad or other input devices that have axes
    If the input devices supports precise scrolling it will also scale the
    numeric value accordingly
    #+begin_src conf :tangle no
      #WHEEL_UP      seek 10
      #WHEEL_DOWN    seek -10
      #WHEEL_LEFT    add volume -2
      #WHEEL_RIGHT   add volume 2
    #+end_src

*** Seek units are in seconds, but note that these are limited by keyframes
    #+begin_src conf :tangle no
      #WHEEL_UP      seek 10
      #RIGHT seek  5
      #LEFT  seek -5
      #UP    seek  60
      #DOWN  seek -60
    #+end_src

*** Do smaller, always exact (non-keyframe-limited), seeks with shift.
    Don't show them on the OSD (no-osd).
    #+begin_src conf :tangle no
      #Shift+RIGHT no-osd seek  1 exact
      #Shift+LEFT  no-osd seek -1 exact
      #Shift+UP    no-osd seek  5 exact
      #Shift+DOWN  no-osd seek -5 exact
    #+end_src
    #+END_SRC

*** Skip to previous/next subtitle
    subject to some restrictions; see manpage
    #+BEGIN_SRC conf :tangle no
      #Ctrl+LEFT   no-osd sub-seek -1
      #Ctrl+RIGHT  no-osd sub-seek  1
    #+END_SRC

*** Adjust timing to previous/next subtitle
    #+BEGIN_SRC conf :tangle no
      #Ctrl+Shift+LEFT sub-step -1
      #Ctrl+Shift+RIGHT sub-step 1
    #+END_SRC

*** Move video rectangle
    #+BEGIN_SRC conf :tangle no
      #Alt+left  add video-pan-x  0.1
      #Alt+right add video-pan-x -0.1
      #Alt+up    add video-pan-y  0.1
      #Alt+down  add video-pan-y -0.1
    #+END_SRC

*** Zoom/unzoom video
    #+BEGIN_SRC conf :tangle input.conf
      =    add video-zoom   0.1
      -    add video-zoom  -0.1
      +    set video-pan-x 0; set video-pan-y 0; set video-zoom 0
    #+END_SRC

*** Reset video zoom/pan settings
    #+BEGIN_SRC conf :tangle no
      #Alt+BS set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0
      #PGUP add chapter 1                     # skip to next chapter
      #PGDWN add chapter -1                   # skip to previous chapter
      #Shift+PGUP seek 600
      #Shift+PGDWN seek -600
      #[ multiply speed 1/1.1                 # scale playback speed
      #] multiply speed 1.1
      #{ multiply speed 0.5
      #} multiply speed 2.0
      #BS set speed 1.0                       # reset speed to normal
      #Shift+BS revert-seek                   # undo previous (or marked) seek
      #Shift+Ctrl+BS revert-seek mark         # mark position for revert-seek
      #q quit
      #Q quit-watch-later
      #q {encode} quit 4
      #ESC set fullscreen no
      #ESC {encode} quit 4
      #p cycle pause                          # toggle pause/playback mode
      #. frame-step                           # advance one frame and pause
      #, frame-back-step                      # go back by one frame and pause
      #SPACE cycle pause
      #> playlist-next                        # skip to next file
      #ENTER playlist-next                    # skip to next file
      #< playlist-prev                        # skip to previous file
      #O no-osd cycle-values osd-level 3 1    # cycle through OSD mode
      #o show-progress
      #P show-progress
      #i script-binding stats/display-stats
      #I script-binding stats/display-stats-toggle
      #` script-binding console/enable
      #z add sub-delay -0.1                   # subtract 100 ms delay from subs
      #Z add sub-delay +0.1                   # add
      #x add sub-delay +0.1                   # same as previous binding (discouraged)
      #ctrl++ add audio-delay 0.100           # this changes audio/video sync
      #ctrl+- add audio-delay -0.100
      #Shift+g add sub-scale +0.1                  # increase subtitle font size
      #Shift+f add sub-scale -0.1                  # decrease subtitle font size
      #9 add volume -2
      #/ add volume -2
      #0 add volume 2
      #* add volume 2
      #m cycle mute
      #1 add contrast -1
      #2 add contrast 1
      #3 add brightness -1
      #4 add brightness 1
      #5 add gamma -1
      #6 add gamma 1
      #7 add saturation -1
      #8 add saturation 1
      #Alt+0 set window-scale 0.5
      #Alt+1 set window-scale 1.0
      #Alt+2 set window-scale 2.0
    #+END_SRC

*** toggle deinterlacer (automatically inserts or removes required filter)
    #+BEGIN_SRC conf :tangle no
      #d cycle deinterlace
      #r add sub-pos -1                       # move subtitles up
      #R add sub-pos +1                       #                down
      #t add sub-pos +1                       # same as previous binding (discouraged)
      #v cycle sub-visibility
    #+END_SRC

*** stretch SSA/ASS subtitles with anamorphic videos to match historical
    #+BEGIN_SRC conf :tangle no
      #V cycle sub-ass-vsfilter-aspect-compat
    #+END_SRC

*** switch between applying no style overrides to SSA/ASS subtitles
    overriding them almost completely with the normal subtitle style
    #+BEGIN_SRC conf :tangle no
      #u cycle-values sub-ass-override "force" "no"
      #j cycle sub                            # cycle through subtitles
      #J cycle sub down                       # ...backwards
      #SHARP cycle audio                      # switch audio streams
      #_ cycle video
      #T cycle ontop                          # toggle video window ontop of other windows
      #f cycle fullscreen                     # toggle fullscreen
      #s screenshot                           # take a screenshot
      #S screenshot video                     # ...without subtitles
      #Ctrl+s screenshot window               # ...with subtitles and OSD, and scaled
      #Alt+s screenshot each-frame            # automatically screenshot every frame
      #w add panscan -0.1                     # zoom out with -panscan 0 -fs
      #W add panscan +0.1                     #      in
      #e add panscan +0.1                     # same as previous binding (discouraged)
    #+END_SRC

*** cycle video aspect ratios; "-1" is the container aspect
    #+BEGIN_SRC conf :tangle no
      #A cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"
      #POWER quit
      #PLAY cycle pause
      #PAUSE cycle pause
      #PLAYPAUSE cycle pause
      #PLAYONLY set pause no
      #PAUSEONLY set pause yes
      #STOP quit
      #FORWARD seek 60
      #REWIND seek -60
      #NEXT playlist-next
      #PREV playlist-prev
      #VOLUME_UP add volume 2
      #VOLUME_DOWN add volume -2
      #MUTE cycle mute
      #CLOSE_WIN quit
      #CLOSE_WIN {encode} quit 4
      #ctrl+w quit
      #E cycle edition                        # next edition
      #l ab-loop                              # Set/clear A-B loop points
      #L cycle-values loop-file "inf" "no"    # toggle infinite looping
      #ctrl+c quit 4
      #DEL script-binding osc/visibility      # cycle OSC display
      #ctrl+h cycle-values hwdec "auto" "no"  # cycle hardware decoding
      #F8 show_text ${playlist}               # show playlist
      #F9 show_text ${track-list}             # show list of audio/sub streams

      #
    #+END_SRC

*** Legacy bindings (may or may not be removed in the future)
    #+BEGIN_SRC conf :tangle no
      #
      #! add chapter -1                       # skip to previous chapter
      #@ add chapter 1                        #         next

      #
    #+END_SRC

*** Not assigned by default
    (not an exhaustive list of unbound commands)
    ? cycle angle                         # switch DVD/Bluray angle
    ? cycle sub-forced-only               # toggle DVD forced subs
    ? cycle program                       # cycle transport stream programs
    ? stop                                # stop playback (quit or enter idle mode)

*** Added by Prady

    #+BEGIN_SRC conf :tangle input.conf
      Z script-binding generate-thumbnails
      Ctrl+r async screenshot
      Ctrl+Shift+r async screenshot video
    #+END_SRC

* mpv Config
** Instructions
*** Warning:
    The commented example options usually do _not_ set the default values. Call
    mpv with --list-options to see the default values for most options. There is
    no builtin or example mpv.conf with all the defaults.
*** Configuration files
    - Are read system-wide from /usr/local/etc/mpv.conf
      per-user from ~/.config/mpv/mpv.conf
      where per-user settings override
      system-wide settings, all of which are overridden by the command line.

    - Configuration file settings and the command line options use the same
      underlying mechanisms. Most options can be put into the configuration file
      by dropping the preceding '--'. See the man page for a complete list of options.
*** Profiles
    Should be placed at the bottom of the configuration file to ensure
    that settings wanted as defaults are not restricted to specific profiles.
** video settings
   #+BEGIN_SRC conf :tangle no
   #+END_SRC

*** Start in fullscreen mode by default.
    #+BEGIN_SRC conf :tangle no
      #fs=yes
    #+END_SRC

*** Force starting with centered window
    #+BEGIN_SRC conf :tangle no
      #geometry=50%:50%

    #+END_SRC

*** Don't allow a new window to have a size larger than 90% of the screen size
    #+BEGIN_SRC conf :tangle no
      #autofit-larger=90%x90%

    #+END_SRC

*** Do not close the window on exit.
    #+BEGIN_SRC conf :tangle no
      #keep-open=yes

    #+END_SRC

*** Do not wait with showing the video window until it has loaded.
    (This will resize the window once video is loaded. Also always shows a window with audio.)
    #+BEGIN_SRC conf :tangle no
      #force-window=immediate

    #+END_SRC

*** Disable the On Screen Controller (OSC).
    Enforce this
    #+BEGIN_SRC conf :tangle mpv.conf
      osc=no
    #+END_SRC
*** Keep the player window on top of all other windows.

    #+BEGIN_SRC conf :tangle no
      #ontop=yes

    #+END_SRC

*** Specify high quality video rendering preset
    for --vo=gpu only
    Can cause performance problems with some drivers and GPUs.
    Default:
      #profile=gpu-hq
    #+BEGIN_SRC conf :tangle mpv.conf
      vo=gpu
    #+END_SRC

*** Force video to lock on the display's refresh rate,
    and change video and audio speed to some degree
    to ensure synchronous playback
    - can cause problems with some drivers and desktop environments.
    #+BEGIN_SRC conf :tangle no
      #video-sync=display-resample

    #+END_SRC

*** Enable hardware decoding if available.
    Often, this does not work with all video outputs, but should work well
    with default settings on most systems.
    If performance or energy usage is an issue,
    forcing the vdpau or vaapi VOs may or may not help.
    #+BEGIN_SRC conf :tangle no
      #hwdec=auto

    #+END_SRC

** audio settings
*** Specify default audio device.
    You can list devices with: --audio-device=help
    The option takes the device string (the stuff between the '...').
    #+BEGIN_SRC conf :tangle no
      #audio-device=alsa/default

    #+END_SRC

*** Do not filter audio to keep pitch when changing playback speed.
    #+BEGIN_SRC conf :tangle no
      #audio-pitch-correction=no

    #+END_SRC

*** Output 5.1 audio natively, and upmix/downmix audio with a different format.
    #+BEGIN_SRC conf :tangle no
      #audio-channels=5.1
    #+END_SRC

*** Disable any automatic remix, _if_ the audio output accepts the audio format.
    of the currently played file. See caveats mentioned in the manpage.
    (The default is "auto-safe", see manpage.)
    #+BEGIN_SRC conf :tangle no
      #audio-channels=auto

    #+END_SRC
** Disguise
*** Pretend to be a web browser.
    Might fix playback with some streaming sites,
    but also will break with shoutcast streams.
    #+BEGIN_SRC conf :tangle no
      #user-agent="Mozilla/5.0"

    #+END_SRC

** Cache settings
*** Use a large seekable RAM cache even for local input.
    #+BEGIN_SRC conf :tangle no
      #cache=yes
      #
    #+END_SRC

*** Use extra large RAM cache (needs cache=yes to make it useful).
    #+BEGIN_SRC conf :tangle no
      #demuxer-max-bytes=500M
      #demuxer-max-back-bytes=100M
      #
    #+END_SRC

*** Disable the behavior that the player will pause if the cache goes below a
    certain fill size.
    #+BEGIN_SRC conf :tangle no
      #cache-pause=no
      #
    #+END_SRC

*** Store cache payload on the hard disk instead of in RAM.
    This may negatively
    impact performance unless used for slow input such as network.
    #+BEGIN_SRC conf :tangle no
      #cache-dir=~/.cache/
      #cache-on-disk=yes

    #+END_SRC

*** Youtube Downloads
    Format
    #+BEGIN_SRC conf :tangle mpv.conf
      ytdl-format=bestvideo[height<=?720]+bestaudio/best
    #+END_SRC

** Language
*** Display English subtitles if available.
    #+BEGIN_SRC conf :tangle mpv.conf
      slang=mr,hi,en
    #+END_SRC

*** Play Marathi audio if available, fall back to Hindi, English otherwise.
    #+BEGIN_SRC conf :tangle mpv.conf
      alang=mr,hi,en
    #+END_SRC

*** Change subtitle encoding. For Arabic subtitles use 'cp1256'.
    If the file seems to be valid UTF-8, prefer UTF-8.
    You can add '+' in front of the codepage to force it.
    #+BEGIN_SRC conf :tangle mpv.conf
      sub-codepage=UTF-8
    #+END_SRC

** Include Path
   #+BEGIN_SRC conf :tangle no
     #include=/path/to/the/file/you/want/to/include
   #+END_SRC
** Profiles
   The options declared as part of profiles override global default settings,
   but only take effect when the profile is active.
** The following profile can be enabled on the command line with: --profile=night
   #+BEGIN_SRC conf :tangle mpv.conf

     [night]
     brightness=-15
   #+END_SRC
