name: Deploy Pages
on:
  push:
    branches:
    - main
    - master
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1

    - name: Copy to Deploy 🔧
      run: |
        mkdir -p public
        cp -t public ./*.html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.
